---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Configure web page
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: "0644"

- name: Enable and start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
