[all]
vm1 ansible_host=89.169.153.68
vm2 ansible_host=93.77.176.188
vm3 ansible_host=111.88.246.121

[proxy]
vm1

[web]
vm2

[proxy:vars]
ansible_ssh_common_args='-o ProxyJump=minder@93.77.176.188'

[all:vars]
ansible_user=minder
ansible_ssh_private_key_file=~/.ssh/id_ed25519
