[proxy]
vm1 ansible_host=93.77.181.145

[web]
vm2 ansible_host=10.128.0.35

[common]
vm3 ansible_host=10.128.0.10

[all:vars]
ansible_user=minder
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[web:vars]
ansible_ssh_common_args='-o ProxyJump=minder@93.77.181.145'

[common:vars]
ansible_ssh_common_args='-o ProxyJump=minder@93.77.181.145'
